///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JGA_RxWebApp_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JGA_RxWebApp_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c9412520-0026-46b6-aef9-d1aae8838932")]
    public partial class JGA_RxWebApp_TestRepository : RepoGenBaseFolder
    {
        static JGA_RxWebApp_TestRepository instance = new JGA_RxWebApp_TestRepository();
        JGA_RxWebApp_TestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the JGA_RxWebApp_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("c9412520-0026-46b6-aef9-d1aae8838932")]
        public static JGA_RxWebApp_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JGA_RxWebApp_TestRepository() 
            : base("JGA_RxWebApp_TestRepository", "/", null, 0, false, "c9412520-0026-46b6-aef9-d1aae8838932", ".\\RepositoryImages\\JGA_RxWebApp_TestRepositoryc9412520.rximgres")
        {
            _applicationundertest = new JGA_RxWebApp_TestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c9412520-0026-46b6-aef9-d1aae8838932")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3560883d-df7f-489a-9273-0c75cf95131e")]
        public virtual JGA_RxWebApp_TestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class JGA_RxWebApp_TestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3560883d-df7f-489a-9273-0c75cf95131e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _budgetguidelightInfo;
            RepoItemInfo _buttonrippleparentInfo;
            RepoItemInfo _buttonbuttonprimaryrippleparentInfo;
            RepoItemInfo _inputrangesliderInfo;
            RepoItemInfo _spantag1994Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='mlp-financify.de']", parentFolder, 30000, null, false, "3560883d-df7f-489a-9273-0c75cf95131e", "")
            {
                _budgetguidelightInfo = new RepoItemInfo(this, "BudgetguideLight", ".//ul[#'mlp-navigation']/?/?/a[@innertext='Budgetguide light']", 30000, null, "32f8d7d4-622b-4219-9e3c-9b14c5047d2f");
                _buttonrippleparentInfo = new RepoItemInfo(this, "ButtonRippleParent", ".//iframe[#'application']//div[#'pgf-light-root']/div/div[2]/div/div", 30000, null, "2ecd24cd-7ba4-4f70-b86d-9a8f9ed39533");
                _buttonbuttonprimaryrippleparentInfo = new RepoItemInfo(this, "ButtonButtonPrimaryRippleParent", ".//iframe[#'application']//div[#'pgf-light-root']//footer/div", 30000, null, "362bb3ab-4de9-49ce-9398-4cb3eb045537");
                _inputrangesliderInfo = new RepoItemInfo(this, "InputRangeSlider", ".//iframe[#'application']//div[#'pgf-light-root']//main/main/div/div/div/?/?/div", 30000, null, "2dffc936-bca3-41ba-bba2-773270a8c5f2");
                _spantag1994Info = new RepoItemInfo(this, "SpanTag1994", ".//iframe[#'application']//div[#'pgf-light-root']//main/main/div/div/div//span[@innertext='1994']", 30000, null, "b09f0d63-d8fe-42b5-9ff5-992d5ff7888c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3560883d-df7f-489a-9273-0c75cf95131e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3560883d-df7f-489a-9273-0c75cf95131e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BudgetguideLight item.
            /// </summary>
            [RepositoryItem("32f8d7d4-622b-4219-9e3c-9b14c5047d2f")]
            public virtual Ranorex.ATag BudgetguideLight
            {
                get
                {
                    return _budgetguidelightInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BudgetguideLight item info.
            /// </summary>
            [RepositoryItemInfo("32f8d7d4-622b-4219-9e3c-9b14c5047d2f")]
            public virtual RepoItemInfo BudgetguideLightInfo
            {
                get
                {
                    return _budgetguidelightInfo;
                }
            }

            /// <summary>
            /// The ButtonRippleParent item.
            /// </summary>
            [RepositoryItem("2ecd24cd-7ba4-4f70-b86d-9a8f9ed39533")]
            public virtual Ranorex.DivTag ButtonRippleParent
            {
                get
                {
                    return _buttonrippleparentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ButtonRippleParent item info.
            /// </summary>
            [RepositoryItemInfo("2ecd24cd-7ba4-4f70-b86d-9a8f9ed39533")]
            public virtual RepoItemInfo ButtonRippleParentInfo
            {
                get
                {
                    return _buttonrippleparentInfo;
                }
            }

            /// <summary>
            /// The ButtonButtonPrimaryRippleParent item.
            /// </summary>
            [RepositoryItem("362bb3ab-4de9-49ce-9398-4cb3eb045537")]
            public virtual Ranorex.DivTag ButtonButtonPrimaryRippleParent
            {
                get
                {
                    return _buttonbuttonprimaryrippleparentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ButtonButtonPrimaryRippleParent item info.
            /// </summary>
            [RepositoryItemInfo("362bb3ab-4de9-49ce-9398-4cb3eb045537")]
            public virtual RepoItemInfo ButtonButtonPrimaryRippleParentInfo
            {
                get
                {
                    return _buttonbuttonprimaryrippleparentInfo;
                }
            }

            /// <summary>
            /// The InputRangeSlider item.
            /// </summary>
            [RepositoryItem("2dffc936-bca3-41ba-bba2-773270a8c5f2")]
            public virtual Ranorex.DivTag InputRangeSlider
            {
                get
                {
                    return _inputrangesliderInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The InputRangeSlider item info.
            /// </summary>
            [RepositoryItemInfo("2dffc936-bca3-41ba-bba2-773270a8c5f2")]
            public virtual RepoItemInfo InputRangeSliderInfo
            {
                get
                {
                    return _inputrangesliderInfo;
                }
            }

            /// <summary>
            /// The SpanTag1994 item.
            /// </summary>
            [RepositoryItem("b09f0d63-d8fe-42b5-9ff5-992d5ff7888c")]
            public virtual Ranorex.SpanTag SpanTag1994
            {
                get
                {
                    return _spantag1994Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag1994 item info.
            /// </summary>
            [RepositoryItemInfo("b09f0d63-d8fe-42b5-9ff5-992d5ff7888c")]
            public virtual RepoItemInfo SpanTag1994Info
            {
                get
                {
                    return _spantag1994Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
