///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace JGA_RxWebApp_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("7a0d4732-7870-42cc-8a50-d0f2633cc266", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the JGA_RxWebApp_TestRepository repository.
        /// </summary>
        public static JGA_RxWebApp_TestRepository repo = JGA_RxWebApp_TestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.BudgetguideLight' at Center.", repo.ApplicationUnderTest.BudgetguideLightInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.BudgetguideLight.DoubleClick();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ButtonRippleParent' at 38;13.", repo.ApplicationUnderTest.ButtonRippleParentInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.ButtonRippleParent.Click("38;13");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ButtonButtonPrimaryRippleParent' at 97;10.", repo.ApplicationUnderTest.ButtonButtonPrimaryRippleParentInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.ButtonButtonPrimaryRippleParent.Click("97;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputRangeSlider' at 11;13.", repo.ApplicationUnderTest.InputRangeSliderInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.InputRangeSlider.Click("11;13");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.InputRangeSlider' at 9;11.", repo.ApplicationUnderTest.InputRangeSliderInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.InputRangeSlider.MoveTo("9;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.InputRangeSlider' at 72;15.", repo.ApplicationUnderTest.InputRangeSliderInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.InputRangeSlider.MoveTo("72;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputRangeSlider' at 13;12.", repo.ApplicationUnderTest.InputRangeSliderInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.InputRangeSlider.Click("13;12");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
